const { test, page, expect } = require('@playwright/test');

test('Visual Comparison to check Navbar existence for mv', async ({ page }) => {

    await page.goto('https://milevision-stage.milezero.com/mv/vueTemplate.jsp?node=RDG');
    await page.getByRole('button', { name: 'AUTH0' }).click()
    await page.getByPlaceholder('username/email').fill("clmsustage")
    await page.getByPlaceholder('your password').fill("1234");
    await page.getByRole('button', { name: 'Log In' }).click();
    await page.goto('https://milevision-stage.milezero.com/mv/vueTemplate.jsp?node=RDG');
    await page.getByText('Toggle Navbar sessionStorage (need to be refresh for other pages): disabled').click();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/fleetLoadReport.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/analyticsPayment.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/history.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/itinerary.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/locationMetrics.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/performance.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/routeMetrics.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/stopMetrics.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/timeline.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/windowMetrics.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/reportsDisplay.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/returnMapEditor.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/routeHub.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/routeManager.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/routes.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/routeView.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/serviceVersions.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/sortAreas.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/sortation.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/sortHistory.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/sortManager.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/ss/Menu.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/swagger/index.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/tipping.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/traceroute_result.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/traceroute.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/tracker.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/vehicle.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/verifiedOrders.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('ttps://milevision-stage.milezero.com/mv/viewLabel.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/workforce.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/wviewer.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/analyticsPayment.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/apacheSSReports.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/apacheSSWrapper.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/bulkSkuPrefs.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/deliveryPerformance.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/plannerServiceTimesConfig.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/plannerWaypointsConfig.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/reportApprovedRoutes.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/reportOrderUpdate.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/storeMetrics.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/transfers.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/zonesConfig.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/activeDrivers.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/addWorker.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/admin/perms.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/areaMap.jsp?node=RDG')
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/assignmentView.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/AuditLogs.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/cleanup.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/clm-workers.jsp?node=RDG');
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    await page.goto('https://milevision-stage.milezero.com/mv/cubMultiDis.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/driverMetrics.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/drivers.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/daily.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/modify.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/multiDispatch.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
    await page.goto('https://milevision-stage.milezero.com/mv/outboundPackagesViewer.jsp?node=RDG');
    await expect.soft(page.getByTitle('Configure').locator('a')).toBeVisible();
    // expect(await page.screenshot()).toMatchSnapshot({ maxDiffPixelRatio: 0.096 });
});